version: '3.5'
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    user: root
    ports:
      - '8086:8086'
      - '8083:8083'
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb/
  jupyter:
    build:
      context: .
      dockerfile: build/jupyter/Dockerfile
    container_name: jupyter
    hostname: jupyter
    restart: unless-stopped
    user: root
    ports:
      - '8888:8888'
    depends_on: 
      - "influxdb"
  grafana:
    build:
      context: .
      dockerfile: build/grafana/Dockerfile
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/grafana:/var/lib/grafana/
    user: root