{
 "title": "Gas Price Monitorization",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filter", "label": "Szürő" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# 🚗 Üzemanyagárak Romániában 🇷🇴"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "options": {
    "content": "\r\n\r\n<table style=\"width:100%; height:100%;border:0px solid black;\">\r\n     <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \">\r\n       <img align=\"center\" src=\"https://econ.ubbcluj.ro/galerie_foto/poze/logo-FSEGA-new-white-01.png\" />\r\n     </td>\r\n</table>"
   }
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "options": {
    "content": "### Naponta frissülő romániai üzemanyagár figyelő, monitorizáló és vizualizáló dashboard, amelynek célja, hogy átfogó képet nyújtson a romániai üzemanyagpiacról.\r\n\r\n---\r\n\r\nAz adatok top-down megközelítésben közli: először romániai szinten, majd megyei, végül kereskedőin.\r\n\r\n_Az adatok naponta (általában 19.30-kor) kerülnek frissítésre a [peco-online.ro](https://www.peco-online.ro/) adatbázisából._  \r\n_A dashboard-ot működtető kód elérhető a [GasPriceMonitorization](https://github.com/rockdonald2/GasPriceMonitorization) GitHub repo-n._  \r\n\r\n2022 | Lukács Zsolt: [elérhetőség](https://www.linkedin.com/in/zsolt-lukacs/)"
   }
  },
  {
   "title": "Mérési pont adata alapján",
   "type": "stat",
   "description": "Magába foglalja minden üzemanyagkút minden üzemanyagtípusának értékét.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Átfogó kép az üzemanyagpiacról", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "📊 Elmúlt periódus átlagárai típusonként",
   "type": "stat",
   "description": "Kiválasztott perióudus országos átlagárai.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Type" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "📈 Típusonként médián és átlagár összehasonlítás",
   "type": "barchart",
   "description": "Medián és átlagár összehasonlítás romániai szinten.",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Type" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "query": "SELECT mean(\"Price\") AS \"Átlag\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE $timeFilter GROUP BY \"Type\"",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Átlag" ], "type": "alias" }
      ]
     ],
     "timefrom": "24h"
    },
    {
     "groupBy": [
      { "params": [ "Type" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "query": "SELECT mean(\"Price\") AS \"Átlag\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE $timeFilter GROUP BY \"Type\"",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Medián" ], "type": "alias" }
      ]
     ],
     "timefrom": "24h"
    }
   ]
  },
  {
   "title": "📈  Elmúlt periódus átlag- és mediánár-fejlődése típusonként",
   "type": "timeseries",
   "description": "Kiválasztott perióudus országos átlagár változásai.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Átlag 95-ös benzinár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Átlag gázolajár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Gázolaj" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Átlag prémium benzinár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Benzin" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Átlag prémium gázolajár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Gázolaj" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Medián 95-ös benzinár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Medián gázolajár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Gázolaj" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Medián prémium benzinár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Benzin" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Médián prémium gázolajár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈  Brent nyersolaj áralakulása",
   "type": "timeseries",
   "description": "Naponta frissített Brent nyersolajár",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "measurement": "CrudeOil",
     "select": [
      [
       { "params": [ "Closing" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "📈 Elmúlt periódus benzinárai",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "measurement": "GasPrice",
     "query": "SELECT \"Price\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE (\"Type\" = '95-ös Benzin') AND $timeFilter",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Elmúlt periódus gázolajárai",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "measurement": "GasPrice",
     "query": "SELECT \"Price\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE (\"Type\" = '95-ös Benzin') AND $timeFilter",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       { "params": [ "Ár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Elmúlt periódus prémium benzinárai",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "measurement": "GasPrice",
     "query": "SELECT \"Price\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE (\"Type\" = '95-ös Benzin') AND $timeFilter",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Elmúlt periódus prémium gázolajárai",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "measurement": "GasPrice",
     "query": "SELECT \"Price\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE (\"Type\" = '95-ös Benzin') AND $timeFilter",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Elmúlt periódus AdBlue árai",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "measurement": "GasPrice",
     "query": "SELECT \"Price\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE (\"Type\" = '95-ös Benzin') AND $timeFilter",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "AdBlue" }
     ]
    }
   ]
  },
  {
   "title": "📈 Elmúlt periódus LPG árai",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "measurement": "GasPrice",
     "query": "SELECT \"Price\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE (\"Type\" = '95-ös Benzin') AND $timeFilter",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "LPG" }
     ]
    }
   ]
  },
  {
   "title": "📈 Átlag üzemanyagárak (95-ös benzin)",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 15, "w": 10, "x": 2, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ISO" ], "type": "tag" },
      { "params": [ "County" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Átlag üzemanyagárak (Gázolaj)",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 15, "w": 10, "x": 12, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ISO" ], "type": "tag" },
      { "params": [ "County" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Átlag üzemanyagárak (Prémium benzin)",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 16, "w": 10, "x": 2, "y": 69 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ISO" ], "type": "tag" },
      { "params": [ "County" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Átlag üzemanyagárak (Prémium gázolaj)",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 16, "w": 10, "x": 12, "y": 69 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ISO" ], "type": "tag" },
      { "params": [ "County" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Legnagyobb üzemanyagárak (95-ös benzin)",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 15, "w": 10, "x": 2, "y": 85 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ISO" ], "type": "tag" },
      { "params": [ "County" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Legnagyobb üzemanyagárak (gázolaj)",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 15, "w": 10, "x": 12, "y": 85 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ISO" ], "type": "tag" },
      { "params": [ "County" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Legnagyobb üzemanyagárak (prémium 95-ös benzin)",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 15, "w": 10, "x": 2, "y": 100 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ISO" ], "type": "tag" },
      { "params": [ "County" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Legnagyobb üzemanyagárak (prémium gázolaj)",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 15, "w": 10, "x": 12, "y": 100 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ISO" ], "type": "tag" },
      { "params": [ "County" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Milyen átlagáron árulnak a kereskedők (95-ös benzin)?",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Vendor" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "query": "SELECT mean(\"Price\") FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE $timeFilter GROUP BY \"Vendor\", \"Type\"",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Milyen átlagáron árulnak a kereskedők (Gázolaj)?",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Vendor" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "query": "SELECT mean(\"Price\") FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE $timeFilter GROUP BY \"Vendor\", \"Type\"",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Milyen átlagáron árulnak a kereskedők (Prémium benzin)?",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Vendor" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "query": "SELECT mean(\"Price\") FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE $timeFilter GROUP BY \"Vendor\", \"Type\"",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Milyen átlagáron árulnak a kereskedők (Prémium gázolaj)?",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Vendor" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "query": "SELECT mean(\"Price\") FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE $timeFilter GROUP BY \"Vendor\", \"Type\"",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Legnagyobb kereskedők átlagárfejlődése (95-ös benzin)",
   "type": "timeseries",
   "description": "Kiválasztott legnagyobb/legnépszerűbb üzemanyagkereskedők kiválasztott periódusra vetített árváltozása a benzin értékesítésében.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "Vendor" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "query": "SELECT mean(\"Price\") AS \"Átlagár\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE (\"Vendor\" = 'OMV' OR \"Vendor\" = 'Gazprom' OR \"Vendor\" = 'Lukoil' OR \"Vendor\" = 'Mol' OR \"Vendor\" = 'Petrom' OR \"Vendor\" = 'Rompetrol') AND \"Type\" = '95-ös Benzin' AND $timeFilter GROUP BY time($interval), \"Vendor\"",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Átlagár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Vendor", "operator": "=", "value": "OMV" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Gazprom" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Lukoil" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Mol" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Petrom" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Rompetrol" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Legnagyobb kereskedők átlagárfejlődése (Gázolaj)",
   "type": "timeseries",
   "description": "Kiválasztott legnagyobb/legnépszerűbb üzemanyagkereskedők kiválasztott periódusra vetített árváltozása a gázolaj értékesítésében.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "Vendor" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "query": "SELECT mean(\"Price\") AS \"Átlagár\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE (\"Vendor\" = 'OMV' OR \"Vendor\" = 'Gazprom' OR \"Vendor\" = 'Lukoil' OR \"Vendor\" = 'Mol' OR \"Vendor\" = 'Petrom' OR \"Vendor\" = 'Rompetrol') AND \"Type\" = 'Gázolaj' AND $timeFilter GROUP BY time($interval), \"Vendor\"",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Átlagár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Vendor", "operator": "=", "value": "OMV" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Gazprom" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Lukoil" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Mol" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Petrom" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Rompetrol" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Legnagyobb kereskedők átlagárfejlődése (Prémium benzin)",
   "type": "timeseries",
   "description": "Kiválasztott legnagyobb/legnépszerűbb üzemanyagkereskedők kiválasztott periódusra vetített árváltozása a prémium benzin értékesítésében.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "Vendor" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "query": "SELECT mean(\"Price\") AS \"Átlagár\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE (\"Vendor\" = 'OMV' OR \"Vendor\" = 'Gazprom' OR \"Vendor\" = 'Lukoil' OR \"Vendor\" = 'Mol' OR \"Vendor\" = 'Petrom' OR \"Vendor\" = 'Rompetrol') AND \"Type\" = 'Prémium Benzin' AND $timeFilter GROUP BY time($interval), \"Vendor\"",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Átlagár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Vendor", "operator": "=", "value": "OMV" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Gazprom" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Lukoil" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Mol" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Petrom" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Rompetrol" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Legnagyobb kereskedők átlagárfejlődése (Prémium gázolaj)",
   "type": "timeseries",
   "description": "Kiválasztott legnagyobb/legnépszerűbb üzemanyagkereskedők kiválasztott periódusra vetített árváltozása a prémium gázolaj értékesítésében.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "Vendor" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "query": "SELECT mean(\"Price\") AS \"Átlagár\" FROM \"GasPriceMonitorization\".\"GasPrice\" WHERE (\"Vendor\" = 'OMV' OR \"Vendor\" = 'Gazprom' OR \"Vendor\" = 'Lukoil' OR \"Vendor\" = 'Mol' OR \"Vendor\" = 'Petrom' OR \"Vendor\" = 'Rompetrol') AND \"Type\" = 'Prémium Gázolaj' AND $timeFilter GROUP BY time($interval), \"Vendor\"",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Átlagár" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Vendor", "operator": "=", "value": "OMV" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Gazprom" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Lukoil" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Mol" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Petrom" },
      { "condition": "OR", "key": "Vendor", "operator": "=", "value": "Rompetrol" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    }
   ]
  },
  {
   "title": "Üzemanyagpiac statisztikai megközelítésben",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 }
  },
  {
   "title": "📈 Benzinár szórás",
   "type": "timeseries",
   "description": "A különböző kereskedők átlagosan hány banival árulták olcsóbban/drágábban a benzint a periódus átlagárához viszonyítva.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       },
       { "params": [ "Átlagtól való eltérés" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Benzinár terjedelem",
   "type": "timeseries",
   "description": "Betekintést nyújt, hogy a kiválasztott periódusban mekkora terjedelemben árultak a különböző kútak benzint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "Terjedelem" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "95-ös Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Gázolajár szórás",
   "type": "timeseries",
   "description": "A különböző kereskedők átlagosan hány banival árulták olcsóbban/drágábban a gázolajt a periódus átlagárához viszonyítva.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       },
       { "params": [ "Átlagtól való eltérés" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Gázolajár terjedelem",
   "type": "timeseries",
   "description": "Betekintést nyújt, hogy a kiválasztott periódusban mekkora terjedelemben árultak a különböző kútak gázolajt.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "Terjedelem" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Prémium benzinár szórás",
   "type": "timeseries",
   "description": "A különböző kereskedők átlagosan hány banival árulták olcsóbban/drágábban a prémium benzint a periódus átlagárához viszonyítva.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       },
       { "params": [ "Átlagtól való eltérés" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Prémium benzinár terjedelem",
   "type": "timeseries",
   "description": "Betekintést nyújt, hogy a kiválasztott periódusban mekkora terjedelemben árultak a különböző kútak prémium benzint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "Terjedelem" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Benzin" }
     ]
    }
   ]
  },
  {
   "title": "📈 Prémium gázolajár szórás",
   "type": "timeseries",
   "description": "A különböző kereskedők átlagosan hány banival árulták olcsóbban/drágábban a prémium gázolajt a periódus átlagárához viszonyítva.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       },
       { "params": [ "Átlagtól való eltérés" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Gázolaj" }
     ]
    }
   ]
  },
  {
   "title": "📈 Prémium gázolajár terjedelem",
   "type": "timeseries",
   "description": "Betekintést nyújt, hogy a kiválasztott periódusban mekkora terjedelemben árultak a különböző kútak prémium gázolajt.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "Terjedelem" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Type", "operator": "=", "value": "Prémium Gázolaj" }
     ]
    }
   ]
  },
  { "title": "Üzemanyagpiac nyersadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 188 } },
  {
   "title": "🗄️ Üzemanyagpiac nyerstáblázata",
   "type": "table",
   "description": "Kiválasztott periódus szerint nyersadatok, város-megye-üzemanyag típus, majd kereskedő szerint csoportosítva.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "RON" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "County" ], "type": "tag" },
      { "params": [ "City" ], "type": "tag" },
      { "params": [ "Vendor" ], "type": "tag" }
     ],
     "measurement": "GasPrice",
     "select": [
      [
       { "params": [ "Price" ], "type": "field" },
       { "params": [ "Ár" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}